# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 784bb2c7b8b269ccc39364ba413e22e901bd2156125cb3f32db1c8d779d7b3bfaadf17df3cb8ec826143d01212de39a37e7edd830df8b6d3c7fefd668873789f

test:
  secret_key_base: f9af9e1c812847d1346de9e5924823b2a6776701f2cf695c22f3241204d2a8b13ec1dd7a145919b0b7888f248c48035732a9a5dcd11f7ce7089205f6349ac33f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
